CREATE TABLE dados (
    id INT AUTO_INCREMENT PRIMARY KEY,
    AlunoID INT NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    Sobrenome VARCHAR(50) NOT NULL,
    Endereco VARCHAR(150) NOT NULL,
    Cidade VARCHAR(50) NOT NULL,
    Host VARCHAR(50) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
